# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:the_world rig_hash set value '50a4db6295ee3436c856f04ff1fdaea6790c6d16dc07bc41fdc344be911bcaf3'
scoreboard objectives add aj.anim.frame dummy
scoreboard objectives add aj.muda_muda.frame dummy