# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:the_world/zzz/reset_floating_entities
execute on passengers if entity @s[tag=aj.the_world.node.head] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.the_world.node.right_arm1] run data merge entity @s { transformation: [-1f,0f,0f,-0.3125f,0f,1f,0f,1.375f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.the_world.node.left_arm1] run data merge entity @s { transformation: [-1f,0f,0f,0.3125f,0f,1f,0f,1.375f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.the_world.node.body] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,0.75f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.the_world.node.left_leg] run data merge entity @s { transformation: [-1f,0f,0f,0.1188f,0f,1f,0f,0.75f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.the_world.node.right_leg] run data merge entity @s { transformation: [-1f,0f,0f,-0.1187f,0f,1f,0f,0.75f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.the_world.node.right_arm2] run data merge entity @s { transformation: [-1f,0f,0f,-0.5625f,0f,1f,0f,1.25f,0f,0f,-1f,-0.0625f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.the_world.node.right_arm3] run data merge entity @s { transformation: [-1f,0f,0f,-0.4375f,0f,1f,0f,1.0625f,0f,0f,-1f,0.125f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.the_world.node.right_arm4] run data merge entity @s { transformation: [-1f,0f,0f,-0.3125f,0f,1f,0f,1.5f,0f,0f,-1f,-0.125f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.the_world.node.left_arm2] run data merge entity @s { transformation: [-1f,0f,0f,0.4375f,0f,1f,0f,1.1875f,0f,0f,-1f,-0.125f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.the_world.node.left_arm3] run data merge entity @s { transformation: [-1f,0f,0f,0.25f,0f,1f,0f,1.3125f,0f,0f,-1f,0.125f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.the_world.node.left_arm4] run data merge entity @s { transformation: [-1f,0f,0f,0.5f,0f,1f,0f,1.5625f,0f,0f,-1f,-0.0625f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.the_world.node.root] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }