# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:the_world/root/on_tick/select_locator_right_arm with entity @s data.locators.right_arm
function animated_java:the_world/root/on_tick/select_locator_left_arm with entity @s data.locators.left_arm