# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.the_world.root] run return 0
execute if entity @s[tag=aj.the_world.animation.anim.playing] run function animated_java:the_world/animations/anim/zzz/on_tick
execute if entity @s[tag=aj.the_world.animation.muda_muda.playing] run function animated_java:the_world/animations/muda_muda/zzz/on_tick
execute on passengers if entity @s[tag=aj.global.data] run function animated_java:the_world/root/on_tick/transform_floating_entities
execute on passengers run rotate @s ~ ~