# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '50a4db6295ee3436c856f04ff1fdaea6790c6d16dc07bc41fdc344be911bcaf3'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack