# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_head) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,0f,0f,0f,0f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_arm1) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,0f,0f,0f,0f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_arm1) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,0f,0f,0f,0f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,0f,0f,0f,0f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_leg) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,0f,0f,0f,0f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_leg) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,0f,0f,0f,0f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_arm2) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,0f,0f,0f,0f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_arm3) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,0f,0f,0f,0f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_arm4) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,0f,0f,0f,0f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_arm2) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,0f,0f,0f,0f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_arm3) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,0f,0f,0f,0f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_arm4) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,0f,0f,0f,0f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"right_arm":{"px":0.8749946725969373,"py":0.000007000376927812428,"pz":0.06250123021635365,"ry":358.3746790918543,"rx":5.101577055452994},"left_arm":{"px":0.8750048258059561,"py":0.0000068181395026736965,"pz":0.06250169147012233,"ry":7.457856554538012e-11,"rx":3.3002380856984027e-11}}}