# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.the_world.node.head] at @s run function animated_java:the_world/variants/steve/zzz/apply_to_node_head
execute on passengers if entity @s[tag=aj.the_world.node.right_arm1] at @s run function animated_java:the_world/variants/steve/zzz/apply_to_node_right_arm1
execute on passengers if entity @s[tag=aj.the_world.node.left_arm1] at @s run function animated_java:the_world/variants/steve/zzz/apply_to_node_left_arm1
execute on passengers if entity @s[tag=aj.the_world.node.body] at @s run function animated_java:the_world/variants/steve/zzz/apply_to_node_body
execute on passengers if entity @s[tag=aj.the_world.node.left_leg] at @s run function animated_java:the_world/variants/steve/zzz/apply_to_node_left_leg
execute on passengers if entity @s[tag=aj.the_world.node.right_leg] at @s run function animated_java:the_world/variants/steve/zzz/apply_to_node_right_leg
execute on passengers if entity @s[tag=aj.the_world.node.right_arm2] at @s run function animated_java:the_world/variants/steve/zzz/apply_to_node_right_arm2
execute on passengers if entity @s[tag=aj.the_world.node.right_arm3] at @s run function animated_java:the_world/variants/steve/zzz/apply_to_node_right_arm3
execute on passengers if entity @s[tag=aj.the_world.node.right_arm4] at @s run function animated_java:the_world/variants/steve/zzz/apply_to_node_right_arm4
execute on passengers if entity @s[tag=aj.the_world.node.left_arm2] at @s run function animated_java:the_world/variants/steve/zzz/apply_to_node_left_arm2
execute on passengers if entity @s[tag=aj.the_world.node.left_arm3] at @s run function animated_java:the_world/variants/steve/zzz/apply_to_node_left_arm3
execute on passengers if entity @s[tag=aj.the_world.node.left_arm4] at @s run function animated_java:the_world/variants/steve/zzz/apply_to_node_left_arm4
return 1