# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_head) {transformation: [0f,0f,0f,0f,0f,0f,0f,0.9375f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_arm1) {transformation: [0f,0f,0f,0f,0f,0f,0f,0.9375f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_arm1) {transformation: [0f,0f,0f,0f,0f,0f,0f,0.9375f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [0f,0f,0f,0f,0f,0f,0f,0.9375f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_leg) {transformation: [0f,0f,0f,0f,0f,0f,0f,0.9375f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_leg) {transformation: [0f,0f,0f,0f,0f,0f,0f,0.9375f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_arm2) {transformation: [0f,0f,0f,0f,0f,0f,0f,0.9375f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_arm3) {transformation: [0f,0f,0f,0f,0f,0f,0f,0.9375f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_arm4) {transformation: [0f,0f,0f,0f,0f,0f,0f,0.9375f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_arm2) {transformation: [0f,0f,0f,0f,0f,0f,0f,0.9375f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_arm3) {transformation: [0f,0f,0f,0f,0f,0f,0f,0.9375f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_arm4) {transformation: [0f,0f,0f,0f,0f,0f,0f,0.9375f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"right_arm":{"px":-0.000004068571987542436,"py":0.9375074111059483,"pz":-0.0000019642422162865983,"ry":33.869853148554085,"rx":3.9336316279324315},"left_arm":{"px":0.000003888573053875132,"py":0.9375063973096198,"pz":1.974268920034913e-7,"ry":6.529365697270606,"rx":-8.465716637673882}}}