# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_head) {transformation: [0f,0f,0f,0f,-0.0572f,2.8106f,-0.7123f,2.5484f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_arm1) {transformation: [0f,0f,0f,0f,0.5243f,2.8354f,-0.3093f,2.0062f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_arm1) {transformation: [0f,0f,0f,0f,-0.2628f,2.8731f,-0.2939f,2.0062f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [0f,0f,0f,0f,0f,2.8916f,-0.221f,0.3797f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_leg) {transformation: [0f,0f,0f,0f,0f,2.9f,0f,0.425f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_leg) {transformation: [0f,0f,0f,0f,0f,2.9f,0f,0.425f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_arm2) {transformation: [0f,0f,0f,0f,0f,0f,0f,1.875f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_arm3) {transformation: [0f,0f,0f,0f,0f,0f,0f,1.3312f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_arm4) {transformation: [0f,0f,0f,0f,0f,0f,0f,2.6f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_arm2) {transformation: [0f,0f,0f,0f,0f,0f,0f,1.6938f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_arm3) {transformation: [0f,0f,0f,0f,0f,0f,0f,2.0563f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_arm4) {transformation: [0f,0f,0f,0f,0f,0f,0f,2.7813f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"right_arm":{"px":-0.0000049841137926446254,"py":0.26684255156124626,"pz":9.802471883547152e-7,"ry":161.5637901847283,"rx":-29.999637785422006},"left_arm":{"px":0.000004470667559300306,"py":0.22694905006975685,"pz":0.0000011377043234917584,"ry":198.4368136886113,"rx":-29.999441257694215}}}