# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
playsound theworld:ability.voiceline player @a[distance=0..64] ~ ~ ~ 4.0 1.0 0.0
function theworld:vfx/summon