# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.muda_muda.frame matches 119.. run scoreboard players set @s aj.muda_muda.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.muda_muda.frame
execute at @s run function animated_java:the_world/animations/muda_muda/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.muda_muda.frame 1