# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:the_world/animations/pause_all
tag @s add aj.the_world.animation.muda_muda.playing
scoreboard players set @s aj.muda_muda.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:the_world/animations/muda_muda/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only